name: Mirror

on:
  push:
    branches: [main, master]
    tags: ['*']

jobs:
  gitlab:
    uses: ALF-QMC/ALF/.github/workflows/mirror-template.yml@master
    with:
      git_url: "git.physik.uni-wuerzburg.de/ALF/ALF"
    secrets:
      GIT_MIRROR_TOKEN: ${{ secrets.GITLAB_MIRROR_TOKEN }}
